Office-ProPlus-Deployment/SelfServiceWebDeployment/SelfService/Controllers/SelfServiceController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using System.Net;
using System.IO;
using Microsoft.Web; 

namespace SelfService.Controllers
{
    public class SelfServiceController : Controller
    {
        //
        // GET: /SelfService/

        public ActionResult Index()
        {
            return View();
        }

        //
        //Get: /SelfService/Languages
        public string Languages()
        {
            return ConfigurationManager.AppSettings["Language"];
        }

        //
        //Get: /SelfService/Products
        public string Products()
        {
            return ConfigurationManager.AppSettings["Product"];
        }

        //
        //Get: /SelfService/Versions
        public string Versions()
        {
            return ConfigurationManager.AppSettings["Version"];
        }
        
        //
        // GET: /SelfService/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /SelfService/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /SelfService/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /SelfService/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /SelfService/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /SelfService/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /SelfService/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        private static void AddLanguages(XDocument doc, IEnumerable<string> languageList){

            foreach (var language in languageList)
            {
                doc?.Root?.Element("Add")?.Element("Product")?.Add(
                    new XElement("Language",
                        new XAttribute("ID", language)));
            } 
        }

        private void CreateQueryString(string xmlPath, string setupPath)
        {
            var baseUrl = Request.Url?.GetLeftPart(UriPartial.Authority);
            if (baseUrl == null) return;
            var builder = new UriBuilder(baseUrl); 
          
            var query = HttpUtility.ParseQueryString(string.Empty);
            query["xmlPath"] = xmlPath;
            query["setupPath"] = setupPath;

            builder.Query = query.ToString();

            Response.Redirect("index.cshtml?xml=" + xmlPath + "&installer=" + setupPath);
        }

        public ActionResult GenerateXml(string buildName, List<string> languageList, string uiLanguage)
        {
            try
            {            
                var currentDirectory = AppDomain.CurrentDomain.BaseDirectory;
                var buildXml = XDocument.Load(currentDirectory + "XmlFiles\\" + buildName + ".xml");

                var generatedXml = new XDocument(buildXml);
                generatedXml.Root?.Element("Add")?.Element("Product")?.Add(
                    new XElement("Language",
                        new XAttribute("ID", uiLanguage)));

                if (languageList.Count > 1)
                {
                    AddLanguages(generatedXml, languageList);
                }

                var fileName = Guid.NewGuid().ToString() + ".xml";
                var saveDir = currentDirectory + "Content\\Generated_Files";
                var savePath = saveDir + @"\" + fileName;

                Directory.CreateDirectory(saveDir);

                generatedXml.Save(savePath);

                var xmlPath = Request.Url?.GetLeftPart(UriPartial.Authority) + HttpRuntime.AppDomainAppVirtualPath + "/Content/Generated_Files/" + fileName ;
                var exePath = Request.Url?.GetLeftPart(UriPartial.Authority) + HttpRuntime.AppDomainAppVirtualPath + "/App/SelfServiceInstaller.application";
                var setupPath = Request.Url?.GetLeftPart(UriPartial.Authority) + HttpRuntime.AppDomainAppVirtualPath + "/Content/Office2016Setup.exe";

                return Json(new { xml = xmlPath, exe = exePath, setup = setupPath });
            }
            catch(Exception e)
            {
                Response.StatusCode = 500;
                string result;
                if (e.Message.Contains("Could not find file"))
                {
                    result = "Base configuration file does not exist for " + buildName;
                }
                else
                {
                    result = e.Message;
                }

                return Json(new { message = result });
            }

        }
    }
}

Office-ProPlus-Deployment/SelfServiceWebDeployment/SelfService/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <title>SelfService</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width"/>
    <link rel="Office Self Service" type="img/png" href="~/favicon.ico"/>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <meta charset="utf-8" name="viewport" content="width=device-width"/>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//appsforoffice.microsoft.com/fabric/1.0.1/fabric.min.css">
    <link rel="stylesheet" href="//appsforoffice.microsoft.com/fabric/1.0.1/fabric.components.min.css">

</head>
<body style="overflow: hidden;">

    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/taggle")
    @RenderSection("scripts", required: false)

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.11.1/typeahead.bundle.min.js"></script>
    <script type="text/javascript" src="./Scripts/FileSaver.js"></script>
    <script type="text/javascript" src="//1000hz.github.io/bootstrap-validator/dist/validator.min.js"></script>
    <script type="text/javascript" src="./Scripts/jquery.fabric.min.js"></script>
    <script type="text/javascript" src="./Scripts/ss.js"></script>

<div id="pageFooter" class="custom-footer footer">
    </div>

    <script>
        $(document).ready(function() {


            if ($('.ms-FilePicker').length > 0) {
                $('.ms-FilePicker').css({
                    "position": "absolute !important"
                });

                $('.ms-Dropdown').FilePicker();
                $('.ms-Toggle').FilePicker();
                $('.ms-Table').FilePicker();
                $('.ms-DatePicker').FilePicker();
            } else {
                if ($.fn.Dropdown) {
                    $('.ms-Dropdown').Dropdown();
                }
                if ($.fn.Toggle) {
                    $('.ms-Toggle').Toggle();
                }
                if ($.fn.Table) {
                    $('.ms-Table').Table();
                }
                if ($.fn.DatePicker) {
                    var myDatepicker = $('.ms-DatePicker').DatePicker({
                        label: "Deadline"
                    });
                }

                if ($.fn.Panel) {
                    $('.ms-Panel').Panel();
                }

                if ($.fn.Dialog) {
                    $('.ms-Dialog').Dialog();
                }

                if ($.fn.List) {
                    $('.ms-List').List();
                }
            }

            if (fabric && fabric['Dropdown']) {
                var component, componentHolder;
                componentHolder = document.querySelector('.component-holder');

                if (componentHolder) {
                    component = new fabric.Spinner(componentHolder);
                }
            }
            if (fabric && fabric['Toggle']) {
                var component, componentHolder;
                componentHolder = document.querySelector('.component-holder');

                if (componentHolder) {
                    component = new fabric.Spinner(componentHolder);
                }
            }
            if (fabric && fabric['Table']) {
                var component, componentHolder;
                componentHolder = document.querySelector('.component-holder');

                if (componentHolder) {
                    component = new fabric.Spinner(componentHolder);
                }
            }
            if (fabric && fabric['DatePicker']) {
                var component, componentHolder;
                componentHolder = document.querySelector('.component-holder');

                if (componentHolder) {
                    component = new fabric.Spinner(componentHolder);
                }
            }

            if (!/Trident/i.test(navigator.userAgent) && !/Edge/i.test(navigator.userAgent)) {
                $(".custom-Dialog").children().empty();
                $(".custom-Dialog").append("<div class='ms-Grid custom-Dialog-main'><div class='ms-Grid-row'>\
                            <div class='ms-Grid-col ms-u-sm12'>\
                        <div class='ms-Grid -header custom-header'>\
                            <div class='ms-Grid-row'>\
                                <div class='ms-font-su'>This site is only accessible via Internet Explorer or Microsoft Edge.</div>\
                        </div></div></div></div></div>");
                $("#productContainer").height(0);
            }

        });
    </script>

    <script>
        var ServerSide = {
            GenerateXML :   '@Url.Action("GenerateXml", "SelfService")'
        }
    </script>
</bodystyle="overflow:>
</html>

Office-ProPlus-Deployment/SelfServiceWebDeployment/SelfService/Views/Shared/_banner.cshtml
@{
    ViewBag.Title = "_banner";
}

<div class="ms-Grid ms-bgColor-themePrimary banner">
    <div class="ms-Grid-row">
        <div class="ms-Grid-col ms-u-sm4">
            <img class="ms-fontColor-white companyLogo" style="height:30px;vertical-align:bottom" />
            <span class="ms-font-xl ms-fontColor-white companyName" style="font-size:22px;padding-right:15px;">
                CompanyLogo/Name
            </span>
        </div>
        <div class="ms-Grid-col ms-u-sm4">
            <span class="ms-font-xl ms-fontColor-white" style="border-left:1px solid white; padding-left:15px;font-size:22px">
                Office Self Service Deployment
            </span>
        </div>
        <div class="ms-Grid-col ms-u-sm4 ms-u-smPush2" onclick="showModal('helpModal')">
            <span id="btAbout" class="ms-fontColor-white ms-Icon ms-Icon--question helpButton"></span>
        </div>
    </div>
</div>

Office-ProPlus-Deployment/SelfServiceWebDeployment/SelfService/Views/Shared/_help.cshtml
@{
    ViewBag.Title = "_help";
}
<div class="custom-Dialog-main">
    <button class="-button custom-back-button" onclick="showModal('productModal')">
        <img class="ms-Icon ms-Icon--x" src="~/Content/imgs/Custom-Back-Arrow.png" />
        <span class="ms-font-l ms-fontWeight-regular">Back</span>
    </button>
    <div class="ms-Dialog-header">
        <p class="-title ms-font-xl">Support Page</p>
        <hr />
    </div>
    <div id="helpContent" class="ms-Dialog-inner custom-Dialog-inner">

    </div>
</div>